spring:
  application:
    name: hellow-talk
  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate.format_sql: true

app:
  jwt:
    secret-key: bXlTdXBlclNlY3JldEtleVRoYXRJc1ZlcnlMb25nQW5kU2VjdXJlMTIz
    expiration-ms: 3600000